### ISSUE TITLE
这是支持单标的的cta还是多标的组合策略？

### ISSUE THREAD

**Issue by choice1983** [veighna-global/vnpy_novastrategy#1]
rt

**Comment by veighna-global** [comment]
NovaStrategy支持多标的策略交易，当然也可以用于运行单标的策略。

和官方的CtaStrategy的区别在于移除了crypto市场不常用的停止单（容易被戳针钓鱼）。

和官方的PortfolioStrategy的区别在于增加了策略模板中on_trade/on_order的支持，通过调整了回测引擎中的撤单机制（T时刻请求，T+1时刻执行）来实现。
